# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
articles = Article.create([
  {id: 1, title: "Top 10 gadgets of 2016", body: "Bacon ipsum dolor amet t-bone jowl sirloin shankle. Sirloin flank filet mignon ribeye beef ribs brisket tail shoulder landjaeger pork chop rump turkey corned beef. Landjaeger shank chicken leberkas kevin. Ball tip cow jowl bresaola swine prosciutto. Spare ribs leberkas prosciutto, andouille meatloaf doner pork pork chop tri-tip kielbasa. Chuck pork belly shank jowl ground round sausage turducken."},
  {id: 2, title: "7 predictions for online video", body: "Bacon ipsum dolor amet t-bone jowl sirloin shankle. Sirloin flank filet mignon ribeye beef ribs brisket tail shoulder landjaeger pork chop rump turkey corned beef. Landjaeger shank chicken leberkas kevin. Ball tip cow jowl bresaola swine prosciutto. Spare ribs leberkas prosciutto, andouille meatloaf doner pork pork chop tri-tip kielbasa. Chuck pork belly shank jowl ground round sausage turducken."},
  {id: 3, title: "5 Skills you must learn in 2016", body: "Bacon ipsum dolor amet t-bone jowl sirloin shankle. Sirloin flank filet mignon ribeye beef ribs brisket tail shoulder landjaeger pork chop rump turkey corned beef. Landjaeger shank chicken leberkas kevin. Ball tip cow jowl bresaola swine prosciutto. Spare ribs leberkas prosciutto, andouille meatloaf doner pork pork chop tri-tip kielbasa. Chuck pork belly shank jowl ground round sausage turducken."},
  {id: 4, title: "3 Terrible Stocks", body: "Bacon ipsum dolor amet t-bone jowl sirloin shankle. Sirloin flank filet mignon ribeye beef ribs brisket tail shoulder landjaeger pork chop rump turkey corned beef. Landjaeger shank chicken leberkas kevin. Ball tip cow jowl bresaola swine prosciutto. Spare ribs leberkas prosciutto, andouille meatloaf doner pork pork chop tri-tip kielbasa. Chuck pork belly shank jowl ground round sausage turducken."},
  {id: 5, title: "2 Cats", body: "Bacon ipsum dolor amet t-bone jowl sirloin shankle. Sirloin flank filet mignon ribeye beef ribs brisket tail shoulder landjaeger pork chop rump turkey corned beef. Landjaeger shank chicken leberkas kevin. Ball tip cow jowl bresaola swine prosciutto. Spare ribs leberkas prosciutto, andouille meatloaf doner pork pork chop tri-tip kielbasa. Chuck pork belly shank jowl ground round sausage turducken."}
  ])